# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='debug',
    version='0.1.0',
    python_requires='==3.*,>=3.7.0',
    author='Kevin Courbet',
    author_email='kevin.courbet.contact@gmail.com',
    packages=['debug'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={"develop": ["pytest==5.*,>=5.2.0"]},
)
